// Libraries
import type { Metadata } from "next";

// Theme Context
import { ThemeProvider } from "@/context/useTheme";

// Components
import Header from "@/Components/Advanced/Header/Header";
import Footer from "@/Components/Advanced/Footer/Footer";
import ContactUs from "@/Components/UIKit/contactUs/ContactUs";

// Styles
import "../Assets/css/index.css";

export const metadata: Metadata = {
  title: "Boldo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider>
          <Header />
          {children}
          <ContactUs />
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
