// Libraries
import type { Metadata } from "next";

// Theme Context
// import { ThemeProvider } from "@/context/useTheme";

// Styles
import "../Assets/css/index.css";
import App from "./App";

export const metadata: Metadata = {
  title: "Boldo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <App>{children}</App>;
}
