// Libraries
import type { Metadata } from "next";

// Components
import Header from "@/Components/Advanced/Header/Header";
import Footer from "@/Components/Advanced/Footer/Footer";

// Styles
import "../Assets/css/index.css";

export const metadata: Metadata = {
  title: "Boldo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
